@startuml
left to right direction
actor Aluno as aluno
actor "Secretaria" as secretaria
actor Professor as professor

usecase "Realizar matrícula" as Matricular
usecase "Cancelar Matrícula" as CancelarMatricula
usecase "Gerar Currículo" as GerarCurriculo
usecase "Gerenciar Períodos de Matrícula" as GerenciarPeriodos
usecase "Gerenciar Disciplinas" as GerenciarDisciplinas
usecase "Consultar Alunos" as ConsultarAlunos
usecase "Notificar sistema de cobrança" as NotificarSistema
usecase "Gerenciar Professores" as GerenciarProfessores
usecase "Gerenciar Alunos" as GerenciarAlunos

aluno --> Matricular
aluno --> CancelarMatricula

secretaria --> GerarCurriculo
secretaria --> GerenciarPeriodos
secretaria --> GerenciarDisciplinas
secretaria --> GerenciarAlunos
secretaria --> GerenciarProfessores

Matricular .> NotificarSistema : include

professor --> ConsultarAlunos
@enduml